name: Build & Push Docker Image

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Image to Github Container Registry
        run: |
          docker build . --tag ghcr.io/h7kz/portfolio-v5:latest
          docker push ghcr.io/h7kz/portfolio-v5:latest
